In [1]:
import pandas as pd

In [8]:
df=pd.read_csv('iris.csv')
df.tail()

sepal.length  sepal.width  petal.length  petal.width    variety
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

In [9]:
df['variety'].value_counts()

Setosa        50
Virginica     50
Versicolor    50
Name: variety, dtype: int64

In [10]:
x=df.iloc[:,0:4].values 

In [12]:
y=df.iloc[:,4].values

In [13]:
from sklearn.preprocessing import LabelEncoder

In [14]:
labelencoder_y= LabelEncoder()

In [15]:
y=labelencoder_y.fit_transform(y)

In [16]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [17]:
from sklearn.model_selection import train_test_split 

In [18]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [19]:
x_train

array([[ 5.8,  2.6,  4. ,  1.2],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5. ,  3.5,  1.6,  0.6],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 6.3,  2.5,  4.9,  1.5],
       [ 5.8,  2.7,  5.1,  1.9],
       [ 6.6,  2.9,  4.6,  1.3],
       [ 4.9,  3.6,  1.4,  0.1],
       [ 7.7,  2.8,  6.7,  2. ],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 6.5,  2.8,  4.6,  1.5],
       [ 6.2,  2.2,  4.5,  1.5],
       [ 5.5,  2.6,  4.4,  1.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 6.9,  3.2,  5.7,  2.3],
       [ 5.1,  3.8,  1.9,  0.4],
       [ 6.7,  3.1,  4.4,  1.4],
       [ 4.5,  2.3,  1.3,  0.3],
       [ 5.6,  2.7,  4.2,  1.3],
       [ 6.4,  2.9,  4.3,  1.3],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 6.1,  2.8,  4. ,  1.3],
       [ 6.7,  3. ,  5. ,  1.7],
       [ 6.2,  2.9,  4.3,  1.3],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 7.1,  3. ,  5.9,  2.1],
       [ 6.3,  2.7,  4.9,  1.8],
       [ 6.7,  3. ,  5.2,  2.3],
       [ 5

In [20]:
x_train.size

420

In [21]:
x_test.size

180

In [22]:
y_train.size

105

In [23]:
y_test.size

45

In [24]:
from sklearn.linear_model import LogisticRegression

In [25]:
logmodel=LogisticRegression()
logmodel.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [26]:
y_pred= logmodel.predict(x_test)

In [51]:
y_pred


array([1, 1, 0, 0, 2, 1, 0, 1, 2, 0, 0, 2, 0, 2, 2, 2, 0, 0, 2, 0, 2, 1, 2,
       2, 0, 1, 1, 2, 0, 2, 0, 2, 1, 1, 0, 0, 2, 1, 1, 1, 2, 2, 1, 2, 2])

In [50]:
np.sort(y_pred)

NameError: name 'np' is not defined

In [28]:
y_test
np.sort(y_test)

NameError: name 'np' is not defined

In [29]:
from sklearn.metrics import confusion_matrix

In [30]:
confusion_matrix(y_test,y_pred)

array([[14,  0,  0],
       [ 0, 12,  0],
       [ 0,  1, 18]])

In [31]:
(28/30)*100

93.33333333333333

In [32]:
logmodel.score(x_test,y_test)

0.97777777777777775

In [33]:
from sklearn.neighbors import KNeighborsClassifier 

In [34]:
classifier_knn= KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)

In [35]:
classifier_knn.fit(x_train,y_train) 

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [36]:
y_pred_knn=classifier_knn.predict(x_test)

In [37]:
y_pred_knn


array([1, 1, 0, 0, 1, 1, 0, 1, 2, 0, 0, 2, 0, 2, 2, 2, 0, 0, 2, 0, 2, 1, 2,
       2, 0, 1, 1, 2, 0, 2, 0, 2, 1, 1, 0, 0, 2, 2, 1, 1, 2, 2, 1, 2, 2])

In [38]:
from sklearn.metrics import confusion_matrix

In [39]:
confusion_matrix(y_test,y_pred_knn)

array([[14,  0,  0],
       [ 0, 12,  0],
       [ 0,  1, 18]])

In [40]:
classifier_knn.score(x_test,y_test)

0.97777777777777775

In [41]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred_knn,y_test)

0.97777777777777775

In [42]:
from sklearn.naive_bayes import GaussianNB

In [43]:
classifier_nb= GaussianNB()

In [44]:
classifier_nb.fit(x_train,y_train)

GaussianNB(priors=None)

In [45]:
y_pred= classifier_nb.predict(x_test)


In [46]:
y_pred

array([1, 1, 0, 0, 2, 1, 0, 1, 2, 0, 0, 2, 0, 2, 2, 2, 0, 0, 2, 0, 2, 1, 2,
       2, 0, 1, 1, 2, 0, 2, 0, 2, 1, 1, 0, 0, 2, 1, 1, 1, 2, 2, 1, 2, 2])

In [47]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred_knn,y_test)

0.97777777777777775

In [48]:
confusion_matrix(y_test,y_pred)

array([[14,  0,  0],
       [ 0, 11,  1],
       [ 0,  2, 17]])

In [49]:
classifier_nb.score(x_test,y_test)

0.93333333333333335